easy_admin:
  site_name: 'FirstForSure'
  translation_domain: 'messages'
  design:
    brand_color: 'green'
    assets:
      js: ['js/jquery-ui.min.js', 'js/admin.js']


    menu:
    - { entity: Position }
    - { entity: Template }
    - { entity: Offer }
  entities:
    Position:
      class: App\Entity\Position
      list:
        fields:
        - { label: 'Pavadinimas', property: 'name' }
        - { label: 'Minutes kaina', property: 'price' }
        - { label: 'Minutes pasiekiamumas', property: 'reach' }
        - { label: 'Likutis', property: 'remaining' }
        - { label: 'Bendras kiekis', property: 'maxQuantity' }
    Template:
      class: App\Entity\Template
      controller: App\Controller\Admin\TemplateAdminController
      list:
        fields:
        - { label: 'Pavadinimas', property: 'title' }
        - { label: 'Pozicijos', property: 'positionTitle' }
        - { label: 'Kaina', property: 'price' }
    Offer:
      class: App\Entity\Offer
      controller: App\Controller\Admin\OfferAdminController
      list:
        fields:
        - { label: 'Gavėjo email', property: 'clientEmail' }
        - { label: 'Gavėjas', property: 'clientName' }

    # List the entity class name you want to manage
#        - App\Entity\Position
#        - App\Entity\PositionTemplate
#        - App\Entity\Template
