easy_admin:
  site_name: 'FirstForSure'
  translation_domain: 'messages'
  design:
    brand_color: 'green'
    assets:
      js: ['js/jquery-ui.min.js', 'js/admin.js']


    menu:
    - { label: 'Reklamos pozicijos ( laikas )', entity: Position }
    - { label: 'Reklamos pozicijos ( vienetas )', entity: PositionWithoutTime }
    - { label: 'Šablonai',entity: Template, role: ROLE_ADMIN}
    - { label: 'Pasiūlymai', entity: Offer }
#    - { label: 'Parduoti pasiūlymai', entity: SoldOffer }
    - { label: 'Užsakymai', entity: BoughtTemplate }
  entities:
    Position:
      class: App\Entity\Position
      label: 'Reklamos pozicijos'
      list:
        title: 'Reklamos pozicijos ( laikas )'
        dql_filter: "entity.hasTime = true"
        fields:
        - { label: 'Pavadinimas', property: 'name' }
        - { label: 'Minutės kaina', property: 'price' }
        - { label: 'Minutės pasiekiamumas', property: 'reach' }
        - { label: 'Likutis', property: 'remaining' }
        - { label: 'Bendras kiekis', property: 'maxQuantity' }
    PositionWithoutTime:
      class: App\Entity\Position
      label: 'Reklamos pozicijos'
      list:
        title: 'Reklamos pozicijos ( vienetas )'
        dql_filter: "entity.hasTime = false"
        fields:
        - { label: 'Pavadinimas', property: 'name' }
        - { label: 'Vieneto kaina', property: 'price' }
        - { label: 'Vieneto pasiekiamumas', property: 'reach' }
        - { label: 'Likutis', property: 'remaining' }
        - { label: 'Bendras kiekis', property: 'maxQuantity' }
    Template:
      class: App\Entity\Template
      label: 'Šablonai'
      controller: App\Controller\Admin\TemplateAdminController
      list:
        title: 'Šablonai'
        dql_filter: "entity.status != 'Nupirkta'"
        fields:
        - { label: 'Pavadinimas', property: 'title' }
        - { label: 'Pozicijos', property: 'positionTitle' }
        - { label: 'Kaina', property: 'price' }
        - { label: 'Pasiekiamumas', property: 'reach' }
    Offer:
      class: App\Entity\Offer
      label: 'Pasiūlymai'
      controller: App\Controller\Admin\OfferAdminController
      list:
        title: 'Pasiūlymai'
        dql_filter: "entity.status != 'Parduota'"
        actions:
        - { label: 'Peržiūrėti', name: 'show'}
        - { label: 'Siųsti', name: 'send'}
        fields:
        - { label: 'Gavėjo email', property: 'clientEmail' }
        - { label: 'Gavėjas', property: 'clientName' }
        - { label: 'Šablonai', property: 'templateList'}
        - { label: 'Statusas', property: 'status' }
#    SoldOffer:
#      class: App\Entity\Offer
#      label: 'Parduoti pasiūlymai'
#      controller: App\Controller\Admin\OfferAdminController
#      actions:
#      - { name: 'show', icon: 'search' }
#      list:
#        title: 'Parduoti pasiūlymai'
#        dql_filter: "entity.status = 'Parduota'"
#        fields:
#        - { label: 'Gavėjo email', property: 'clientEmail' }
#        - { label: 'Gavėjas', property: 'clientName' }
#        - { label: 'Šablonai', property: 'templateList'}
#        - { label: 'Statusas', property: 'status' }
    BoughtTemplate:
      class: App\Entity\BoughtTemplate
      label: 'Užsakymai'
      list:
        title: 'Užsakymai'
        fields:
        - { label: 'Pasiūlymas', property: 'offer' }
        - { label: 'Užsakymas', property: 'template' }

    # List the entity class name you want to manage
#        - App\Entity\Position
#        - App\Entity\PositionTemplate
#        - App\Entity\Template
