easy_admin:
  site_name: 'FirstForSure'
  translation_domain: 'messages'
  design:
    assets:
      js: ['js/jquery-ui.min.js', 'js/admin.js']
      css: ['css/bootstrap.css','css/bootstrap-theme.css','css/styles.css']

    menu:
    - { entity: Position }
    - { entity: Template }
  entities:
    Position:
      class: App\Entity\Position
      list:
        fields:
        - { label: 'Pavadinimas', property: 'name' }
        - { label: 'Minutes kaina', property: 'price' }
        - { label: 'Minutes pasiekiamumas', property: 'reach' }
        - { label: 'Likutis', property: 'remaining' }
        - { label: 'Bendras kiekis', property: 'maxQuantity' }
    Template:
      class: App\Entity\Template
      controller: App\Controller\Admin\TemplateAdminController
      list:
        fields:
        - { label: 'Pavadinimas', property: 'title' }
        - { label: 'Pozicijos', property: 'positionTemplates' }
    # List the entity class name you want to manage
#        - App\Entity\Position
#        - App\Entity\PositionTemplate
#        - App\Entity\Template
