framework:
    default_locale: 'lt'
    translator:
#        default_path: '%kernel.project_dir%/translations'
        fallbacks:
            - 'lt'
#
#framework:
#    default_locale: 'en'
#    translator:
#        paths:
#        - '%kernel.project_dir%/translations'
#        fallbacks: ['en']
