#easy_admin_bundle:
#    resource: '@EasyAdminBundle/Controller/AdminController.php'
#    prefix: /admin
#    type: annotation
easy_admin_bundle:
    resource: '@EasyAdminExtensionBundle/Controller/AdminController.php'
    type:     annotation
    prefix:   /admin
