index:
    path: /
    controller: App\Controller\HomeController::index

readoffer:
    path: /readoffer/{md5}
    controller: App\Controller\HomeController::reademail

logout:
    path: /logout

admin_template:
    path: /admin/?entity=Template&action=list&menuIndex=3&submenuIndex=-1

admin_dashboard:
    path: /admin/dashboard

admin_template_create:
    path: /create/template
    controller: App\Controller\Admin\TemplateAdminController::makeTemplate

admin_offer_create:
    path: /create/offer
    controller: App\Controller\Admin\OfferAdminController::makeOffer

user_offer_confirm:
    path: /offer/confirm
    controller: App\Controller\Admin\OfferAdminController::confirmOffer