index:
    path: /
    controller: App\Controller\HomeController::index

basicform:
    path: /basicform
    controller: App\Controller\HomeController::new

readoffer:
    path: /readoffer/{md5}
    controller: App\Controller\HomeController::reademail
